### ISSUE TITLE
Memory index immediate vs. operand

### ISSUE THREAD

**Issue by pepyakin** [WebAssembly/multi-memory#1]
I read that the memory instructions will receive a memory index immediate. That means there is no way to write code that is agnostic to the memory it is located. I wonder if a memory index specified via an operand is on the table?

**Comment by rossberg** [comment]
That would require first-class references to memories. That is something that has been discussed a couple of times, but it is a way more advanced extension and beyond the scope of this specific proposal. Here, we just introduce the same thing we already have for table and globals.

**Comment by pepyakin** [comment]
Maybe I am missing something, but why are memory references needed? I was more thinking about extending memory instructions in such a way that they would require an i32 operand which specifies the memory index on which to perform the operation. Instead of adding a set of new instructions a new bitflag could be devoted in existing ones which if enabled makes these instructions to take a new operand with the memory index.

I have no idea how it might be supported on the toolchain side though. I suspect that augmenting a pointer with additional memory index might just not work.

**Comment by rossberg** [comment]
Static index spaces and dynamic operands are completely disjoint universes. If you could select a static index with a dynamic operand then all sorts of things would break, e.g., you could no longer merge modules. You'll need an indirection through a table to do that, as for functions. But that would require the ability to put references to memory objects into tables.

**Comment by pepyakin** [comment]
Ah, now I see, thanks!
