### ISSUE TITLE
How would multiple memories work with function imports?

### ISSUE THREAD

**Issue by wcaughey** [WebAssembly/multi-memory#10]
First of all, apologies if this is not the right place for feedback and questions.  If this isn't the right place then just let me know what is.

It looks like from the proposed specification that _memidx_ is contained in the immediate part of the memory instructions meaning that when a function is compiled it statically binds to a specific memory in the target module.  But suppose same function was then exported and then imported into a separate module; is it expected that the this function would still be bound to this same _memindex_ in the new module?  If so, then this seems problematic--either the opportunity for code reuse by importing functions becomes limited to just those situations where the _memindex_ in the exporting module and the importing module happen to align, or the importer would need some way to specify which memories a given imported function binds.

**Comment by binji** [comment]
> But suppose same function was then exported and then imported into a separate module; is it expected that the this function would still be bound to this same memindex in the new module? 

It would be bound to the memory with the same [memory address](https://webassembly.github.io/spec/core/exec/runtime.html#addresses) in the store. The memory index is local to the module. You can already see this behavior with functions and globals:

```wasm
(module $A
  (func (export "f0") ...)  ;; func 0 in module $A
  (func (export "f1" ...) ;; func 1 in module $A
  (global (export "g0") ...)  ;; global 0 in module $A
  (global (export "g1") ...)  ;; global 1 in module $A
)
(module $B
  (import "A" "f1" (func ...)) ;; func 0 in module $B
  (import "A" "f0" (func ...)) ;; func 1 in module $B
  (import "A" "g1" (global ...)) ;; global 0 in module $B
  (import "A" "g0" (global ...)) ;; global 1 in module $B

  (func $test
    ...
   call 0  ;; calls $A.f1
  )
)
```

**Comment by wcaughey** [comment]
Ah, thanks for the response!  So just to clarify, if function F, defined in module A had a load instruction that read from some offset of memory M of the same module, then if F were imported into module B, that load instruction would still read from memory M, even if M was not imported into B, correct?

**Comment by binji** [comment]
Right, you can think of the function instance as implicitly closing over its module instance. As another example:

```wasm
(module $A
  ;; This memory is not exported.
  (memory $M 1)
  ;; This function is exported, and always accesses memory $M. 
  (func (export "f")
    ...
    i32.load ;; This loads implicitly from memory $M
    ...
  )
)
```

This module only defines one export, the function `f`. When you call this function, it will always use its module's own memory, regardless of who calls it.

**Comment by wcaughey** [comment]
Awesome, thanks for the clarification!
