### ISSUE TITLE
Data segment syntax incompatible with bulk-memory-operations proposal

### ISSUE THREAD

**Issue by Connicpu** [WebAssembly/multi-memory#11]
I ran into this issue while trying to test a WASM compiler that implements both of the multi-memory and bulk-memory-operations specs.

So in the multi-memory proposal the load.wast test contains the following module:

```wat
(module
  (memory $mem1 (import "M" "mem") 2)
  (memory $mem2 3)

  (data $mem1 (i32.const 20) "\01\02\03\04\05")
  (data $mem2 (i32.const 50) "\0A\0B\0C\0D\0E")

  (func (export "read1") (param i32) (result i32)
    (i32.load8_u $mem1 (local.get 0))
  )
  (func (export "read2") (param i32) (result i32)
    (i32.load8_u $mem2 (local.get 0))
  )
)
```

Unfortunately as the bulk-memory-operations proposal requires, the data segments are parsed as having labels "mem1" and "mem2", instead of initializing those memories. To make this test compatible with the bulk-mem syntax, only a small change is required:

```wat
  (data (memory $mem1) (i32.const 20) "\01\02\03\04\05")
  (data (memory $mem2) (i32.const 50) "\0A\0B\0C\0D\0E")
```

It may be a good idea to change the multi-memory syntax to the bulk-memory-operations version since it's the more general one that would support both proposals.

**Comment by rossberg** [comment]
Fixed by #12. Once the bulk proposal has landed in the main spec and we merge that here, there will be additional work changing the new memory instructions.
