### ISSUE TITLE
Text format for data segments may be confusing with passive data segments

### ISSUE THREAD

**Issue by alexcrichton** [WebAssembly/multi-memory#13]
According to the [current rendered spec](https://webassembly.github.io/multi-memory/core/text/modules.html#data-segments) the text format for data segments attached to non-index-zero memories is:

```wasm
(data $mem (i32.const 0) "...")
```

but I think this could be confusing and difficult to parse with data segments that are otherwise named for passive segment initialization:

```wasm
(data $foo "...")

;; ...
memory.init $foo
```

Perhaps `data` attached to a nonzero memory could be parsed similarly to `elem` segments with nonzero tables?

```wasm
;; currently used for tables
(elem $elem_segment_id (table $a) (i32.const 0) (; ... ;) )

;; possibility for memory
(data $data_segment_id (memory $a) (i32.const 0) (; ... ;) )
```

**Comment by rossberg** [comment]
Yeah, this was already changed in the bulk-ops proposal, so I didn't bother changing it here since I thought that lands in master soon and I can just rebase. But everything is going slow, so I manually incorporated that change in #14.

**Comment by alexcrichton** [comment]
Oh awesome, thanks!
