### ISSUE TITLE
Binary format is out of date

### ISSUE THREAD

**Issue by titzer** [WebAssembly/multi-memory#16]
The decoder in this branch is out of date with the bulk-memory-operations branch.

In particular, for data segments:

This repo:
```
let segment dat s =
  let index = at var s in
  let offset = const s in
  let init = dat s in
  {index; offset; init}                                                                                                                
```

Bulk memory:
```
let data s =
  match vu32 s with
  | 0x00l ->
    let dmode = at active_zero s in
    let dinit = string s in
    {dinit; dmode}
  | 0x01l ->
    let dmode = at passive s in
    let dinit = string s in
    {dinit; dmode}                                                                                                                     
  | 0x02l ->
    let dmode = at active s in
    let dinit = string s in
    {dinit; dmode}
  | _ -> error s (pos s - 1) "invalid data segment kind"
```

I.e. it appears this repo is interpreting the reserved 0 byte as `i32` index, when it should be a flags bitfield, with bit 6 indicating the presence of a memory segment index.

**Comment by binji** [comment]
Yeah, this proposal probably should have taken a dependency on bulk-memory. Those should [merge into the upstream spec soon](https://github.com/WebAssembly/spec/pull/1242), so at that point we can merge these changes here too.

**Comment by rossberg** [comment]
Right, I'll rebase once the upstream merge has happened.

**Comment by vshymanskyy** [comment]
Was this resolved?
