### ISSUE TITLE
Possibility to dynamically add memories at runtime?

### ISSUE THREAD

**Issue by tomaka** [WebAssembly/multi-memory#19]
I couldn't figure out the answer by reading the overview.
Is it planned to be able for host functions to add more memories to an already-running Wasm instance?

There are a couple of use cases that would need this:

- A Wasm module could ask the host to spawn another Wasm module, in which case it is desirable to share a memory between the parent and the child for "inter-process" ("inter-instance") communication.
- Implementing some equivalent to `mmap`.

Might be related to https://github.com/WebAssembly/multi-memory/issues/9

**Comment by rossberg** [comment]
Dynamic memory creation would essentially require first-class memories, i.e., a sort of `memoryref` type and corresponding instructions. That is certainly a useful feature, but far more involved (both design and implementation-wise), and hence out of scope for the current proposal. This one is merely a straightforward generalisation of the existing memory semantics that mirrors what we already did for tables.

**Comment by rossberg** [comment]
Closing this since it's out of scope of this proposal.
