### ISSUE TITLE
Additional test cases for multi-memory

### ISSUE THREAD

**Issue by titzer** [WebAssembly/multi-memory#39]
When testing the Wizard implementation of multi-memory, I looked into spectest coverage for the feature. There are a few tests for multi-memory, but I unless I overlooked something, I didn't find many.

In this https://github.com/titzer/wizard-engine/commit/a41d70c8c8f49277733856ead5cbdefb4be8eb50 commit, I copied+mutated most spec tests that reference memories to have multi-memory variations.

I'd like to contribute these tests to the spec repo, as I think they are valuable. The reference interpreter passes all of them.

**Comment by rossberg** [comment]
Please do!

**Comment by rossberg** [comment]
Tests have been merged.
