### ISSUE TITLE
Is there a way to access a non-hardcoded memory?

### ISSUE THREAD

**Issue by Daniel-Abrecht** [WebAssembly/multi-memory#51]
The load and store instructions include a memidx, so they hard code which memory they are to access.  
Ideally, I would like to have pointers that include both the memory index and the offset in it's value. I would like to be able to create functions that I can use for any memories. But if I understand how this currently works correctly, that's not currently possible? At least, not unless I essentially make a big switch case for all my memories for every load and store?

**Comment by rossberg** [comment]
Right. Anything beyond that would essentially require first-class memory references (like function references), to store them in tables, where they can be dynamically indexed. That is a reasonable extension that some of us would like to see as well eventually, but it's outside the scope of this proposal and would be far more involved for engines.

**Comment by Daniel-Abrecht** [comment]
I see. Thank you for the quick response.
