### ISSUE TITLE
A Bug in multi memory test?

### ISSUE THREAD

**Issue by TianlongLiang** [WebAssembly/multi-memory#52]
```wat
(module
  (memory (export "memory-2-inf") 2)
  (memory (export "memory-2-4") 2 4)
)

(register "test")

(module
  (import "test" "memory-2-4" (memory 1))
  (memory $m (import "spectest" "memory") 0 3)  ;; actual has max size 2
  (func (export "grow") (param i32) (result i32) (memory.grow $m (local.get 0)))
)
(assert_return (invoke "grow" (i32.const 0)) (i32.const 1))
(assert_return (invoke "grow" (i32.const 1)) (i32.const 1))
(assert_return (invoke "grow" (i32.const 0)) (i32.const 2))
(assert_return (invoke "grow" (i32.const 1)) (i32.const -1))
(assert_return (invoke "grow" (i32.const 0)) (i32.const 2))
```

I think it's a bug in [this file](https://github.com/WebAssembly/multi-memory/blob/c2c00d81cbc1a9a4a8c2411bebbb7151d8cc492b/test/core/multi-memory/imports4.wast#L13). Per my understanding, one memory's initial size should be irrelevant to another memory's size, as it's shown in [other file like this](https://github.com/WebAssembly/multi-memory/blob/main/test/core/multi-memory/memory_size1.wast)

**Comment by rossberg** [comment]
The first size in a memory type declares the minimum size, which only coincides with an initial size in actual definitions. Subtyping on limits [requires](https://webassembly.github.io/spec/core/valid/types.html#match-limits) that the min is ≥ and the max is ≤ in the subtype compared to the supertype.

**Comment by TianlongLiang** [comment]
Thanks for your reply, I forgot it's the `(memory (export "memory") 1 2)` in the predefined spectest module
