### ISSUE TITLE
Spec for instantiation of active data segments is incorrect

### ISSUE THREAD

**Issue by CharlieTap** [WebAssembly/multi-memory#54]
The [spec](https://webassembly.github.io/multi-memory/core/exec/modules.html#instantiation) still states:

![image](https://github.com/user-attachments/assets/dbe09614-85e6-4b27-a809-085b2d6d5f60)

However when I left this validation check in my runtime it fails the multi-memory testsuite so I imagine that this check is no longer necessary.

**Comment by rossberg** [comment]
Thanks! Fixed now.
