### ISSUE TITLE
Alignment test failure on the latest testsuite

### ISSUE THREAD

**Issue by CharlieTap** [WebAssembly/multi-memory#55]
I also posted this here: https://github.com/WebAssembly/testsuite/issues/96

Effectively the latest testsuite has tests for exponents greater than 64 which falls into the condition where the mem index is encoded, and thus fails. The proposal should probably copy align.wast and alter those tests to account for the exponent subtraction.

**Comment by CharlieTap** [comment]
Looks like it might have failed one of the CI checks

**Comment by rossberg** [comment]
That looks like node.js failing one of the tests. Maybe it's current V8 isn't up-to-date enough?
