### ISSUE TITLE
Zero copy and 2D context

### ISSUE THREAD

**Issue by penzn** [WebAssembly/multi-memory#7]
[HTML Canvas][2d] provides [CanvasRenderingContext][c] which uses [ImageData][i] handle to interface with a byte array. Interface with all of this via Wasm requires creating `ImageData` from a byte array and requires copying the array from `ImageData` into module's memory. It might be possible to do zero copy access to rendering context or image data directly using functionality from this proposal if one of those types exported `WebAssembly.Memory()`.

Also see whatwg/html#5173

[2d]: https://html.spec.whatwg.org/multipage/canvas.html
[c]: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D
[i]: https://developer.mozilla.org/en-US/docs/Web/API/ImageData

**Comment by rossberg** [comment]
@penzn, I can't tell, are you suggesting some extension to this proposal, or would this be an extension to the DOM? In the latter case, let's close this here and move discussion to a more appropriate place.
