### ISSUE TITLE
Additional motivation: efficient memory mapping

### ISSUE THREAD

**Issue by ratchetfreak** [WebAssembly/multi-memory#9]
An application may want to map en external buffer and read/write to it directly. 

A concrete example is mapping a webgl vertex buffer into a wasm module to have it filled out based by decoding a model file.

**Comment by SamuraiCrow** [comment]
If a non-web encoding was able to mark a region as volitile, memory-mapped I/O based device drivers could be implemented in WebAssembly.  (If this isn't currently possible at this late state of proposal, I'm likely to add this to a new proposal.)

**Comment by dschuff** [comment]
This has been discussed in the context of a new proposal we call "memory control" (See https://github.com/WebAssembly/memory-control and the [discussion](https://github.com/WebAssembly/design/issues/1439) proposing it)

**Comment by SamuraiCrow** [comment]
@dschuff Thanks for the links!
